spring:
  cloud:
    config:
      profile: docker # Default profile is docker.
jwt:
  secret: 1A50EF4F7AB1F6069BC04EEABFA52D66257D47E7FBBE0D7C1C20D2D88E9489C5
  expiration: 86400000 # 1 day
  refresh-expiration:  1296000000 # 15 days
  issuer: http://localhost:9000