spring:
  application:
    name: workspaces
  config:
    import: optional:configserver:${spring.cloud.config.uri}
  cloud:
    config:
      uri: http://localhost:8888
  datasource:
    username: intralogix
    password: password
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/intralogix-db
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: true
server:
  port: 8502
